name: Publish on crates.io

on:
  release:
    types:
      - released

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}

    name: Build ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: cargo check

  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cargo fmt
        run: cargo fmt
      - name: cargo clippy
        run: cargo clippy

  publish:
    runs-on: ubuntu-latest
    needs:
      - build
      - lints
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}