name: Rust CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}

    name: Build ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: cargo check

  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cargo fmt
        run: cargo fmt
      - name: cargo clippy
        run: cargo clippy